# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
---
project_name: revive
before:
  hooks:
    - "go mod tidy"
    - "go generate ./..."
archives:
  # - id: archive-deprecated
  #   replacements:
  #     386: i386
  #     amd64: x86_64
  #     darwin: Darwin
  #     linux: Linux
  #     windows: Windows
  - id: archive-compatible-name
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
  - id: latest-version-independant
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
builds:
  - env:
      - CGO_ENABLED=0
      - BUILDER=GoReleaser
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      # Default GoReleaser ldflags
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
      # ldflags from the repo's Makefile as of 2023-02-18
      - -X "github.com/mgechev/revive/cli.version={{.Version}}" 
      - -X "github.com/mgechev/revive/cli.date={{.Date}}" 
      - -X "github.com/mgechev/revive/cli.commit={{.Commit}}" 
      - -X "github.com/mgechev/revive/cli.builtBy={{.Env.BUILDER}}"
dockers:
  - image_templates:
      - "ghcr.io/mgechev/revive:{{ .Version }}"
      - "ghcr.io/mgechev/revive:{{ .Tag }}"
      - "ghcr.io/mgechev/revive:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/mgechev/revive:v{{ .Major }}"
      - "ghcr.io/mgechev/revive:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - "--label=org.opencontainers.image.description=🔥 ~6x faster, stricter, configurable, extensible, and beautiful drop-in replacement for golint"
      - --label=org.opencontainers.image.url=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.source=https://github.com/mgechev/revive
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  sort: asc
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
